spring:
  application:
    name: config-server
  threads:
    virtual:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka

server:
  port: 8085

env: default
